package sample;
// Generated Sep 14, 2016 9:59:20 PM by Hibernate Tools 4.3.1



/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private int id;
     private String one;
     private String two;

    public Test() {
    }

	
    public Test(int id) {
        this.id = id;
    }
    public Test(int id, String one, String two) {
       this.id = id;
       this.one = one;
       this.two = two;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getOne() {
        return this.one;
    }
    
    public void setOne(String one) {
        this.one = one;
    }
    public String getTwo() {
        return this.two;
    }
    
    public void setTwo(String two) {
        this.two = two;
    }




}


